apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: pivdnwyva-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/pivdnwyva-java-quarkus-gitops